#!/usr/bin/env node
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import yaml from 'js-yaml';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(HERE, '..', 'src', 'lib', 'github', 'catalog.generated.ts');

const LINGUIST_URL =
  'https://raw.githubusercontent.com/github-linguist/linguist/main/lib/linguist/languages.yml';
const TOPIC_QUERIES = ['is:featured', 'is:curated'];
const TOPICS_PAGES = 10;

/**
 * [목적] Linguist YAML과 Featured Topics를 받아 `src/lib/github/catalog.generated.ts`를 덮어쓴다.
 * [주의] 빌드 타임이 아니라 수동 실행용(`pnpm sync:catalog`). 생성 파일은 레포에 커밋해
 *        Vercel 빌드 중 네트워크 의존을 없앤다.
 *        GitHub API rate limit을 위해 GITHUB_TOKEN 환경변수를 지정할 수 있다.
 */
async function main() {
  const token = process.env.GITHUB_TOKEN;

  const [languages, topics] = await Promise.all([
    fetchLanguages(),
    fetchFeaturedTopics(token),
  ]);

  const ts = renderCatalogFile({ languages, topics });
  await writeFile(OUT_PATH, ts, 'utf8');
  console.log(
    `✓ wrote ${OUT_PATH} (${languages.length} languages, ${topics.length} topics)`,
  );
}

async function fetchLanguages() {
  const response = await fetch(LINGUIST_URL);
  if (!response.ok) {
    throw new Error(`linguist fetch failed: ${response.status} ${response.statusText}`);
  }
  const raw = await response.text();
  const parsed = yaml.load(raw);
  if (!parsed || typeof parsed !== 'object') {
    throw new Error('linguist YAML parse returned non-object');
  }

  const entries = [];
  for (const [name, value] of Object.entries(parsed)) {
    if (!value || typeof value !== 'object') continue;
    if (value.type !== 'programming') continue;
    entries.push({
      name,
      slug: name.trim().toLowerCase().replace(/\s+/g, '-'),
      color: typeof value.color === 'string' ? value.color : null,
    });
  }
  const seen = new Set();
  const unique = [];
  for (const entry of entries) {
    if (seen.has(entry.slug)) continue;
    seen.add(entry.slug);
    unique.push(entry);
  }
  unique.sort((a, b) => a.name.localeCompare(b.name));
  return unique;
}

async function fetchFeaturedTopics(token) {
  const topics = new Map();
  const headers = {
    Accept: 'application/vnd.github.mercy-preview+json',
    'User-Agent': 'ossfit-sync-catalog',
  };
  if (token) headers.Authorization = `Bearer ${token}`;

  outer: for (const queryQualifier of TOPIC_QUERIES) {
    for (let page = 1; page <= TOPICS_PAGES; page += 1) {
      const url = `https://api.github.com/search/topics?q=${encodeURIComponent(queryQualifier)}&per_page=100&page=${page}`;
      const response = await fetch(url, { headers });
      if (response.status === 403 || response.status === 429) {
        console.warn(
          `! rate limit hit on q=${queryQualifier} page=${page}; stopping topic sync (set GITHUB_TOKEN to fetch more).`,
        );
        break outer;
      }
      if (!response.ok) {
        const body = await response.text();
        throw new Error(
          `topics fetch failed q=${queryQualifier} page=${page}: ${response.status} ${response.statusText} ${body}`,
        );
      }
      const payload = await response.json();
      const items = Array.isArray(payload.items) ? payload.items : [];
      if (items.length === 0) break;
      for (const item of items) {
        if (!item || typeof item.name !== 'string') continue;
        const slug = item.name.trim().toLowerCase();
        if (!slug) continue;
        if (topics.has(slug)) continue;
        topics.set(slug, {
          name: slug,
          displayName:
            typeof item.display_name === 'string' && item.display_name.length > 0
              ? item.display_name
              : slug,
          description:
            typeof item.short_description === 'string' &&
            item.short_description.length > 0
              ? item.short_description
              : null,
        });
      }
      if (items.length < 100) break;
    }
  }

  return [...topics.values()].sort((a, b) =>
    a.displayName.localeCompare(b.displayName),
  );
}

function renderCatalogFile({ languages, topics }) {
  const header = `// AUTO-GENERATED by scripts/sync-catalog.mjs — do not edit by hand.
// Source: Linguist languages.yml (${LINGUIST_URL})
//         GitHub Topics: ${TOPIC_QUERIES.join(', ')}
// Run \`pnpm sync:catalog\` to refresh.

export type CatalogLanguage = {
  name: string;
  slug: string;
  color: string | null;
};

export type CatalogTopic = {
  name: string;
  displayName: string;
  description: string | null;
};

`;

  const languageLines = languages
    .map(
      (lang) =>
        `  { name: ${JSON.stringify(lang.name)}, slug: ${JSON.stringify(lang.slug)}, color: ${JSON.stringify(lang.color)} },`,
    )
    .join('\n');

  const topicLines = topics
    .map(
      (topic) =>
        `  { name: ${JSON.stringify(topic.name)}, displayName: ${JSON.stringify(topic.displayName)}, description: ${JSON.stringify(topic.description)} },`,
    )
    .join('\n');

  return `${header}export const LANGUAGE_CATALOG: readonly CatalogLanguage[] = [
${languageLines}
];

export const TOPIC_CATALOG: readonly CatalogTopic[] = [
${topicLines}
];
`;
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
